🚧 Make readme into an actual cheatsheet format
inato/fp-ts-cheatsheet pull request #21
Opened 2022-04-12 10:19 UTC by Punie

[Rendered](https://github.com/inato/fp-ts-cheatsheet/blob/rework-cheatsheet/README.md)

Todo:
- [ ] `map` / `chain`
- [ ] `sequence` / `traverse`
- [ ] `Do-notation`
- [ ] Fix table of contents
- [ ] Link to more documentation

2022-04-13 10:08 UTC, vinassefranche commented on README.md
> +import { Option } from 'fp-ts/Option';
I'd remove this one as it's redundant with the line above

2022-04-13 10:10 UTC, vinassefranche commented on README.md
>  const noneValue = option.none;
I would update the examples above so they use these two options instead of creating them twice. This would save a bit of space in the file

2022-04-13 10:10 UTC, vinassefranche commented on README.md
> +// Pro-tip: option.match is short for the following:
not sure I would keep this in the cheatsheet

2022-04-13 10:12 UTC, vinassefranche commented on README.md
> +either.fromOption('value was nullish')(someValue); // => either.right('value')
```suggestion
either.fromOption(() => 'value was nullish')(noneValue); // => either.left('value was nullish')
either.fromOption(() => 'value was nullish')(someValue); // => either.right('value')
```

2022-04-13 10:14 UTC, vinassefranche commented on README.md
>      console.log(`The error was ${eitherError}`);
```suggestion
    console.log(`The error was ${error}`);
```

2022-04-13 10:14 UTC, vinassefranche commented on README.md
> +// Pro-tip: either.match is short for the following:
same as for Option

2022-04-13 10:17 UTC, vinassefranche commented on README.md
> +taskEither.fromOption('value was nullish')(someValue); // => taskEither.right('value')
I think I would not rewrite all these here and it's 'just' a port of the `Either`. Maybe just a sentence listing that `fromNullable`, `fromPredicate` and `fromOption` exists just like for `Either` could be enough

2022-04-13 10:18 UTC, vinassefranche commented on README.md
> +// Build an Either
```suggestion
// Build a TaskEither
```

2022-04-13 10:18 UTC, vinassefranche commented on README.md
> +  await sleep(1000);
we don't really need this

2022-04-13 10:22 UTC, vinassefranche commented on README.md
> +either.getOrElse(() => 0)(eitherValue); // => 42
Maybe we can also add the `taskEither.getOrElse`:
```
const someTaskEither = taskEither.right(42);
const task = taskEither.getOrElse(async () => 0)(eitherValue); // => task.of(42)
await task(); // => 42
```

2022-04-13 10:26 UTC, vinassefranche commented on README.md
> +);
I think it would have some value to add example for `findFirst`, `compact`, `head` and `tail`

2022-04-13 10:27 UTC, vinassefranche commented on README.md
> +## <a name="array"></a>Array and ReadonlyArray
We should only talk about ReadonlyArray (here and the examples below)

2022-04-13 10:30 UTC, vinassefranche requested changes
There are some small things to fix but it's a big improvement!

2022-04-13 13:14 UTC, Punie commented on README.md
> +await someTask(); // => 42
Yes that's a good point.
I'm still thinking about how to structure the cheatsheet tbh.

But yeah, adding a short `Task` section and a note that `TaskEither` is a convenience for working with `Task<Either>` should be the way to go.

2022-04-13 14:02 UTC, vinassefranche commented on README.md
> +// Pro-tip: option.match is short for the following:
I agree it has great value. Maybe we could move it to the details page or have some training exercises on this specific topic

2022-04-13 14:07 UTC, vinassefranche approved these changes
Great!

2022-04-14 06:37 UTC, merged

2022-04-14 06:37 UTC, Punie commented
I'm merging this and will continue the rework in a separate PR